### ISSUE TITLE
windows下路径问题

### ISSUE THREAD

**Issue by Edinjohn** [li24361/sorryJava#10]
windows下获取到的路径地址是反斜杠
cmd下ffmpeg 只能认第一个反斜杠的路径
GifService.java中应把assPath  gifPath  videoPath中的反斜杠替换成正斜杠

**Comment by li24361** [comment]
有空我试一下，或者你提个pr，谢谢

**Comment by yujiain2008** [comment]
win 命令ffmpeg -i E:/sorryJava/cache/sorry/template.mp4 -r 5 -vf ass=demo.ass,scale=180:-1 -y E:/sorryJava/cache/demo.gif
可行
 ass好像不能绝对路径 有盘符

**Comment by yujiain2008** [comment]
最简单的字幕ass文件可这样
[Script Info]

[Aegisub Project Garbage]

[V4+ Styles]

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.08,0:00:03.80,Default,,0,0,0,,haha1
Dialogue: 0,0:00:03.80,0:00:05.80,Default,,0,0,0,,haha2
Dialogue: 0,0:00:05.80,0:00:07.80,Default,,0,0,0,,haha3
Dialogue: 0,0:00:07.80,0:00:08.90,Default,,0,0,0,,haha4
Dialogue: 0,0:00:08.90,0:00:09.50,Default,,0,0,0,,haha5
Dialogue: 0,0:00:09.50,0:00:10.90,Default,,0,0,0,,haha6
Dialogue: 0,0:00:10.90,0:00:13.30,Default,,0,0,0,,haha7
Dialogue: 0,0:00:13.30,0:00:14.90,Default,,0,0,0,,haha8
Dialogue: 0,0:00:14.90,0:00:16.90,Default,,0,0,0,,haha9
