### ISSUE TITLE
linux下ffmpeg问题

### ISSUE THREAD

**Issue by David1013** [li24361/sorryJava#11]
[AVFilterGraph @ 0x1c95c40] No such filter: 'ass'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
windows下没有问题，但是到服务器出现这个问题，是ffmpeg安装的姿势不对？

**Comment by li24361** [comment]
`在服务器上建立文件夹/opt/site/cache/sorry 下载template.mp4跟template.ftl放进去`

这个操作了吗

**Comment by David1013** [comment]
操作了，现在生成个空的gif
ERROR>ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
ERROR>  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-18)
ERROR>  configuration: --enable-shared --prefix=/root/ffmpeg
ERROR>  libavutil      55. 78.100 / 55. 78.100
ERROR>  libavcodec     57.107.100 / 57.107.100
ERROR>  libavformat    57. 83.100 / 57. 83.100
ERROR>  libavdevice    57. 10.100 / 57. 10.100
ERROR>  libavfilter     6.107.100 /  6.107.100
ERROR>  libswscale      4.  8.100 /  4.  8.100
ERROR>  libswresample   2.  9.100 /  2.  9.100
ERROR>Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/sorry/catch/sorry/template.mp4':
ERROR>  Metadata:
ERROR>    major_brand     : isom
ERROR>    minor_version   : 512
ERROR>    compatible_brands: isomiso2avc1mp41
ERROR>    encoder         : Lavf56.40.101
ERROR>    description     : Packed by Bilibili XCoder v1.0(fixed_gap:False)
ERROR>  Duration: 00:00:20.88, start: 0.000000, bitrate: 249 kb/s
ERROR>    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 300x168 [SAR 399:400 DAR 57:32], 119 kb/s, 8 fps, 8 tbr, 16384 tbn, 16 tbc (default)
ERROR>    Metadata:
ERROR>      handler_name    : VideoHandler
ERROR>    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
ERROR>    Metadata:
ERROR>      handler_name    : SoundHandler
ERROR>Stream mapping:
ERROR>  Stream #0:0 -> #0:0 (h264 (native) -> gif (native))
ERROR>Press [q] to stop, [?] for help
ERROR>[AVFilterGraph @ 0x1aa3c40] No such filter: 'ass'
ERROR>Error reinitializing filters!
ERROR>Failed to inject frame into filter network: Invalid argument
ERROR>Error while processing the decoded data for stream #0:0
ERROR>Conversion failed!

**Comment by li24361** [comment]
字体安装了吗？

**Comment by David1013** [comment]
字体也安装了

**Comment by li24361** [comment]
/opt/site/cache 可以看下这下面是否生成了.ass文件

**Comment by David1013** [comment]
.ass确实生成了，查了ffmpeg也确实支持ass，但是ffmpeg不是按照你的说明文档装的，执行你说明文档命令装后很顺利是么？不然我考虑重装下ffmpeg

**Comment by li24361** [comment]
按照我的命令安装下试试

**Comment by NoviceZHB** [comment]
新手怎么才能弄好这些然后制作动图
