### ISSUE TITLE
可不可以通过图片生成gif不是视频

### ISSUE THREAD

**Issue by yujiain2008** [li24361/sorryJava#12]
你好，这个是不是只能通过视频生成gif，能不能通过gif图片生成新的gif图片

**Comment by li24361** [comment]
需要用ffmpeg将图片转成视频再转成gif吧，主要被处理速度限制，所以还是建议用视频直接转

**Comment by yujiain2008** [comment]
可不可以把元gif添加自定义字幕的，这个好像要视频还有些文件
