### ISSUE TITLE
nohup: ignoring input and appending output to ‘nohup.out’

### ISSUE THREAD

**Issue by 1135890950** [li24361/sorryJava#13]
小白想问一下进行到这一步的时候
![qq 20180624054021](https://user-images.githubusercontent.com/40441060/41813883-66af452c-7771-11e8-92be-c1687f935816.png)
出现这个nohup: ignoring input and appending output to ‘nohup.out’
怎么解决？
系统centos7.3  装的宝塔面板 Tomact7 和jdk1.7，环境变量也没有问题
就剩这个不知道怎么解决！

**Comment by li24361** [comment]
这个没什么问题,已经启动起来了啊
