### ISSUE TITLE
关于mac系统安装ffmpeg的问题

### ISSUE THREAD

**Issue by ghost** [li24361/sorryJava#17]
请添加关于mac系统安装ffmpeg的详细操作描述，mac系统下无法使用yum工具安装，需要安装类似yum的工具如：brew：
`$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
然后使用命令安装ffmpeg：
`$ brew install ffmpeg`

**Comment by li24361** [comment]
谢谢, 已添加
