### ISSUE TITLE
建议不添加 giflossy

### ISSUE THREAD

**Issue by CoXier** [li24361/sorryJava#2]
从我的测试来看，giflossy 对于gif的压缩时间需要大概在2~3s，如果此项目部署在服务器端，延迟较严重。

**Comment by li24361** [comment]
giflossy 是python的，你说的是gifsicle ？

**Comment by CoXier** [comment]
giflossy 是从 gifsicle 克隆而来，均是 C 写的。因为某些原因，这两个库现在分开了，现在 giflossy 的整体效果要优于 gifsicle
