### ISSUE TITLE
关于window系统，执行FFmpeg ass文件路径的问题。

### ISSUE THREAD

**Issue by wuwei1993** [li24361/sorryJava#22]
window 系统，执行FFmpeng  命令 是 ass 文件 不能是绝对路径，绝对路径会报错：
[Parsed_ass_0 @ 000001d20187acc0] Shaper: FriBidi 1.0.4 (SIMPLE)
[Parsed_ass_0 @ 000001d20187acc0] Using font provider directwrite
[Parsed_ass_0 @ 000001d20187acc0] ass_read_file(..ae1bb83b38e9402485c83ef3455b64f5.ass): fopen failed
[Parsed_ass_0 @ 000001d20187acc0] Could not create a libass track when reading file '..ae1bb83b38e9402485c83ef3455b64f5.ass'
[AVFilterGraph @ 000001d27fe4bec0] Error initializing filter 'ass' with args '..ae1bb83b38e9402485c83ef3455b64f5.ass'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0

**Comment by li24361** [comment]
你把命令单独copy出来在cmd里面执行试试, 排除权限问题,相对路径和绝对路径都是一样的啊

**Comment by KID5945** [comment]
这个windows绝对路径确实有问题，改成相对路径执行方式
用下面的执行方法，增加dir参数，此命令相当于在dir目录下执行
Process exec = Runtime.getRuntime().exec(cmd,null,dir);
