### ISSUE TITLE
初学java，学习一下。

### ISSUE THREAD

**Issue by DDreame** [li24361/sorryJava#7]
在直接运行jar包以后远程网页访问ip并不能打开网页，百度了一些资料，我是不是应该自己打包成war包然后用tomcat来运行?还是我端口哪些没有打开？我用的是阿里云，系统centOS7，希望得到一个回复。能稍微指点方向即可。谢谢

**Comment by DDreame** [comment]
已经解决。阿里云网页后台开一个8888端口即可。谢谢。

**Comment by li24361** [comment]
哦，我用的是腾讯云，看来阿里云是要单独打开8888端口的？
