### ISSUE TITLE
生成出来是空的呢

### ISSUE THREAD

**Issue by LKonn** [li24361/sorryJava#8]

**Comment by li24361** [comment]
是自己搭建的还是我的demo呢？

**Comment by LKonn** [comment]
你的demo  我把命令弄到cmd直接执行   ass文件报了几个错

**Comment by li24361** [comment]
看下是否是windows环境，然后ass文件路径包含了盘符

**Comment by li24361** [comment]
可以把命令和错误信息给我一下

**Comment by LKonn** [comment]
应该就是盘符的问题了
C:\Users\Administrator>ffmpeg -i E:\opt\site\cache\sorry\template.mp4 -r 6 -vf a
ss=E:\opt\site\cache\97ff4b5f61854150bfede0b410c23fdd.ass,scale=300:-1 -y E:\opt
\site\cache\3f4cd686-0bc0-425e-84cd-e1e9047e346c.gif

**Comment by li24361** [comment]
这个问题我也研究了蛮久的，暂时没找到解决方案，加引号，改参数都试过了
