### ISSUE TITLE
mvn命令打包失败

### ISSUE THREAD

**Issue by ywp0919** [li24361/sorryJava#9]
$ mvn package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.lzh:sorry-java >-------------------------
[INFO] Building sorryJava 1.4.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sorry-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ sorry-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\sorryJava\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.445 s
[INFO] Finished at: 2018-04-25T11:49:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sorry-java: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

大佬，我jdk也有配置在环境变量，git clone 下来后 用mvn这个命令来打包的时候失败了，麻烦指教一下，谢谢

**Comment by li24361** [comment]
No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

**Comment by ywp0919** [comment]
但是java -version也能看到jdk版本信息，在环境变量也有配置

**Comment by ywp0919** [comment]
已解决。close吧
